
services:

  test:
    build:
      context: .
      target: test
    depends_on:
      postgresql:
        condition: service_healthy

  createuser:
    build: .
    mem_limit: 512m
    env_file:
      - ${FILE_ENV_FOR_APPLICATION}
#    environment:
#      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
    ports:
      - "8443:8443"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: createUserInAuth0-db
    image: postgres:15.13
    mem_limit: 512m
    # this mapping can be removed in production. For now, we keep it to access the DB from the IDE.  logger:
    #    image: alpine
    #    command:
    #      - /bin/sh
    #      - -c
    #      - "echo Valeur de DOMAIN_NAME : ${OKTA_OAUTH2_AUDIENCE} && sleep infinity"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=createUserInAuth0
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d createUserInAuth0"]
      interval: 5s
      timeout: 2s
      retries: 60
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:

