spring:
  application:
    name: createUserInAuth0
  cloud:
    openfeign:
      okhttp:
        enabled: true
  jackson:
    mapper:
      sort-properties-alphabetically: true

mavariable:
  profile: default

