spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/createUserInAuth0
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/common
    schemas: public
    clean-disabled: false

server:
  port: ${SERVER_PORT}
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-alias: localhost

mavariable:
  profile: ${MA_VARIABLE_PROFILE}

auth0:
  domain: ${AUTH0_DOMAIN}
  auth0_management_api:
    clientId: ${AUTH0_MANAGEMENT_API_CLIENT}
    clientSecret: ${AUTH0_MANAGEMENT_API_CLIENTSECRET}
    audience: ${AUTH0_MANAGEMENT_API_AUDIENCE}
  client_origin_url: ${CLIENT_ORIGIN_URL}
  functional_user:
    clientId: ${FUNCTIONAL_API_CLIENT}
    clientSecret: ${FUNCTIONAL_API_CLIENTSECRET}
    audience: ${FUNCTIONAL_API_AUDIENCE}

#usertestforcreation:
#  email: ${USERTESTFORCREATION_EMAIL}
#  connection: ${USERTESTFORCREATION_CONNECTION}
#  password: ${USERTESTFORCREATION_PASSWORD}

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}

logging:
  level:
    com.oidccall.createUserInAuth0.controllers: debug
    com.oidccall.createUserInAuth0: debug
    root: ${LOG_LEVEL_ROOT:info}  # niveau par défaut pour tous les autres packages
    org.springframework.boot.autoconfigure.logging: ERROR
    org.springframework.boot.autoconfigure.condition: ERROR

