mavariable:
  profile: ${MA_VARIABLE_PROFILE}

auth0:
  domain: ${AUTH0_DOMAIN}
  testapplication:
    auth0_management_api:
      clientId: ${AUTH0_MANAGEMENT_API_CLIENT}
      clientSecret: ${AUTH0_MANAGEMENT_API_CLIENTSECRET}
      audience: ${AUTH0_MANAGEMENT_API_AUDIENCE}

usertestforcreation:
  email: ${USERTESTFORCREATION_EMAIL}
  connection: ${USERTESTFORCREATION_CONNECTION}
  password: ${USERTESTFORCREATION_PASSWORD}


logging:
  level:
    com.oidccall.createUserInAuth0.controllers: debug
    root: ${LOG_LEVEL_ROOT:info}  # niveau par défaut pour tous les autres packages

