CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER');

create table public.users
(
    id               bigint generated by default as identity primary key,
    auth0_user_id    varchar(35) not null unique,
    created_by       varchar(100),
    created_at       timestamp(6) with time zone not null default now(),
    email            varchar(200) not null,
    gender           gender_type,
    last_modified_by varchar(100),
    modified_at      timestamp(6) with time zone not null default now(),
    picture          varchar(255),
    nickname         varchar(100),
    given_name       varchar(100),
    family_name      varchar(100),
    email_verified    boolean not null default false,
    last_modified_email_verified timestamp(6) with time zone not null default now(),
    phone_number     varchar(50),
    enabled          boolean not null default true,
    deleted          boolean not null default false
);

CREATE UNIQUE INDEX uk_users_email_enabled ON users (email) WHERE deleted = false;
CREATE UNIQUE INDEX uk_users_phone_number_enabled ON users (phone_number) WHERE deleted = false;

alter table public.users owner to "user";
alter sequence public.users_id_seq owner to "user";

CREATE TABLE public.authorities
(
    id BIGINT generated by default as identity primary key,
    users_id BIGINT NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY(users_id) REFERENCES users(id)
);
