create table public.users_deleted
(
    id               	bigint generated by default as identity primary key,
    auth0_user_id    	varchar(35) not null unique,
    created_by       	varchar(100),
    created_at       	timestamp(6) with time zone not null,
    email            	varchar(200) not null,
    gender           	gender_type,
    last_modified_by 	varchar(100),
    modified_at      	timestamp(6) with time zone not null,
    picture          	varchar(255),
    nickname        	varchar(100),
    given_name       	varchar(100),
    family_name      	varchar(100),
    email_verified   	boolean not null,
    email_status     	email_status_type not null,
    last_modified_email_verified timestamp(6) with time zone not null,
    phone_number     	varchar(50),
    job_execution_id 	bigint,
    step_name 			varchar(30)
);


alter table public.users_deleted owner to "user";
alter sequence public.users_deleted_id_seq owner to "user";
