create table batch_to_users
(
    id                  bigint generated by default as identity primary key,
    job_execution_id    bigint not null,
    step_name 			varchar(30),
    email_status        email_status_type,
    user_id             bigint
        constraint batch_to_users_users_id_fk
            references users (id)
            on delete cascade,
    created_at          timestamp(6) with time zone default now() not null,
    modified_at         timestamp(6) with time zone default now() not null
);

alter table batch_to_users
    owner to "user";

