create table public.restaurateur
(
    id               bigint generated by default as identity primary key,
    name             varchar(150),
    adresse          varchar(200),
    telephone        varchar(50),
    email            varchar(150),
    created_at       timestamp(6) with time zone not null default now(),
    updated_at       timestamp(6) with time zone not null default now(),
    active           boolean not null default true,
    monthly_price    numeric(3, 2),
    currency         varchar(3)
);

alter table public.restaurateur owner to "user";
alter sequence public.restaurateur_id_seq owner to "user";
