create table public.template
(
    id               bigint generated by default as identity primary key,
    restaurateur_id  bigint not null,
    name             varchar(150),
    active           boolean not null default true,
    monday           boolean not null default false,
    tuesday          boolean not null default false,
    wednesday        boolean not null default false,
    thursday         boolean not null default false,
    friday           boolean not null default false,
    saturday         boolean not null default false,
    sunday           boolean not null default false,
    data_solo        date,
    valid_from       date,
    created_at       timestamp(6) with time zone not null default now(),
    updated_at       timestamp(6) with time zone not null default now(),
    comment          varchar(255),
    constraint fk_template_restaurateur
        foreign key (restaurateur_id)
            references public.restaurateur (id)
            on delete cascade
);

alter table public.template owner to "user";
alter sequence public.template_id_seq owner to "user";