create table public.client
(
    id         integer generated by default as identity primary key,
    name       varchar(30),
    firstname  varchar(30),
    phone      varchar(30),
    email      varchar(60),
    code       varchar(10),
    created_at timestamp(6) with time zone not null default now(),
    updated_at timestamp(6) with time zone not null default now()
);

alter table public.client owner to "user";
alter sequence public.client_id_seq owner to "user";