create table public.reservation
(
    id               integer generated by default as identity primary key,
    restaurateur_id  bigint not null,
    template_id      bigint not null,
    table_number     varchar(10) not null,
    client_id        integer not null,
    reservation_date date not null,
    start_time       time not null,
    end_time         time not null,
    nb_person        integer not null,
    create_at        timestamp(6) with time zone not null default now(),
    update_at        timestamp(6) with time zone not null default now(),
    constraint fk_reservation_restaurateur
        foreign key (restaurateur_id)
            references public.restaurateur (id)
            on delete cascade,
    constraint fk_reservation_client
        foreign key (client_id)
            references public.client (id)
            on delete cascade,
    constraint fk_reservation_service_capacity
        foreign key (template_id, restaurateur_id, table_number)
            references public.service_capacity (template_id, restaurateur_id, table_number)
            on delete cascade
);

alter table public.reservation owner to "user";
alter sequence public.reservation_id_seq owner to "user";