
CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER');

create table public.users
(
    id               bigint generated by default as identity primary key,
    auth0_user_id    varchar(35) not null unique,
    created_by       varchar(100),
    created_at       timestamp(6) with time zone not null default now(),
    email            varchar(200) not null unique,
    gender           gender_type,
    last_modified_by varchar(100),
    modified_at      timestamp(6) with time zone not null default now(),
    picture          varchar(255),
    username         varchar(100) not null,
    phone_number     varchar(50) unique
);

alter table public.users owner to "user";

-- create sequence public.users_id_seq;
alter sequence public.users_id_seq owner to "user";
-- alter sequence public.users_id_seq owned by public.users.id;


CREATE TABLE authorities
(
    id BIGINT generated by default as identity primary key,
    users_id BIGINT NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY(users_id) REFERENCES users(id)
);


